### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by ShengyuH** [chrischoy/gesvd#2]
hi Chris, 

Under a virtual env, I successfully install gesvd via python setup.py install. I can find it in pip list:
```
(torch) shenhuan@pf-pc30:.../MinkowskiEngine$ cd ..
(torch) shenhuan@pf-pc30:.../shengyu$ pip show gesvd
Name: gesvd
Version: 0.1
Summary: UNKNOWN
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /scratch/shengyu/torch/lib/python3.6/site-packages/gesvd-0.1-py3.6-linux-x86_64.egg
Requires: 
Required-by: 
```

But when importing it, it reports module not found:
```
(torch) shenhuan@pf-pc30:.../shengyu$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gesvd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gesvd'
```

I install MinkowskiEngine in the same way and can import it, here is pip show message:
```
(torch) shenhuan@pf-pc30:.../shengyu$ pip show MinkowskiEngine
Name: MinkowskiEngine
Version: 0.4.2
Summary: a convolutional neural network library for sparse tensors
Home-page: https://github.com/StanfordVL/MinkowskiEngine
Author: Christopher Choy
Author-email: chrischoy@ai.stanford.edu
License: UNKNOWN
Location: /scratch/shengyu/torch/lib/python3.6/site-packages/MinkowskiEngine-0.4.2-py3.6-linux-x86_64.egg
Requires: numpy, torch
Required-by:
```

Do you have any clues where might be wrong?

**Comment by Aelphy** [comment]
Probably, related:

nm -a gesvd_cpp.cpython-36m-x86_64-linux-gnu.so | grep svd
                 U dgesvd_
0000000000000000 a gesvd.cpp
                 U sgesvd_

Two functions from lapack dgesvd_ and sgesvd_ are undefined

**Comment by Aelphy** [comment]
the problem is that the lib is not linked with lapack,
fixed with
`
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/gesvd.o -o build/lib.linux-x86_64-3.6/gesvd_cpp.cpython-36m-x86_64-linux-gnu.so -lopenblas
`
after installation and one needs also to replace gesvd_cpp.cpython-36m-x86_64-linux-gnu.so in the install location with one from build/lib.linux-x86_64-3.6/

**Comment by ShengyuH** [comment]
> the problem is that the lib is not linked with lapack,
> fixed with
> `x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/gesvd.o -o build/lib.linux-x86_64-3.6/gesvd_cpp.cpython-36m-x86_64-linux-gnu.so -lopenblas`
> after installation and one needs also to replace gesvd_cpp.cpython-36m-x86_64-linux-gnu.so in the install location with one from build/lib.linux-x86_64-3.6/

Thanks, this fixes the error, when using 
```
python setup.py develop
```

**Comment by gujiaqivadin** [comment]
Hello, @ShengyuH @Aelphy  . I found the same problem as yours. Can you give a brief solution to solve the 'no module named gesvd 'problem. Thanks very much！
